a = float(input("số thứ nhất: "))
b = float(input("số thứ hai: "))
print(f"lũy thừa: {a**b}")
print(f"Căn2 của {a}: {a**0.5}")
print(f"Căn2 của {b}: {b**0.5}")
print(f"phần nguyên: {a//b}")
print(f"phần thập phân: {a%b}")
print(f"làm tròn {a}: {round(a)}")
print(f"làm tròn {b}: {round(b)}")